//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCodeGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFCodeGenerator.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, ORDINAL_POSITION, (select columnproperty(object_id(TABLE_NAME),COLUMN_NAME,&apos;IsIdentity&apos;)) as &apos;IS_IDENTITY&apos; FROM INFORMATION_SCHEMA.COLUMNS 
        ///order by TABLE_SCHEMA, TABLE_NAME,ORDINAL_POSITION.
        /// </summary>
        internal static string SelectColumns {
            get {
                return ResourceManager.GetString("SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  obj.name AS FK_NAME,
        ///    sch.name AS [schema_name],
        ///    tab1.name AS [table],
        ///    col1.name AS [column],
        ///    tab2.name AS [referenced_table],
        ///    col2.name AS [referenced_column]
        ///FROM sys.foreign_key_columns fkc
        ///INNER JOIN sys.objects obj
        ///    ON obj.object_id = fkc.constraint_object_id
        ///INNER JOIN sys.tables tab1
        ///    ON tab1.object_id = fkc.parent_object_id
        ///INNER JOIN sys.schemas sch
        ///    ON tab1.schema_id = sch.schema_id
        ///INNER JOIN sys.columns col1
        ///    ON col1.column_id = parent_column_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectForeignKeys {
            get {
                return ResourceManager.GetString("SelectForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME, TABLE_NAME, TABLE_SCHEMA,CONSTRAINT_NAME
        ///FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
        ///WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + &apos;.&apos; + QUOTENAME(CONSTRAINT_NAME)), &apos;IsPrimaryKey&apos;) = 1.
        /// </summary>
        internal static string SelectPrimaryKeys {
            get {
                return ResourceManager.GetString("SelectPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE=&apos;BASE TABLE&apos;
        ///order by TABLE_SCHEMA, TABLE_NAME.
        /// </summary>
        internal static string SelectTables {
            get {
                return ResourceManager.GetString("SelectTables", resourceCulture);
            }
        }
    }
}
